### ISSUE TITLE
Missing summernote-image-shapes.js

### ISSUE THREAD

**Issue by khiav223577** [DiemenDesign/summernote-image-shapes#1]
I'm looking for old Image Shapes functionality of `summernote`.
This issue https://github.com/summernote/summernote/issues/1902 leads me to [summernote-image-attributes](https://github.com/StudioJunkyard/summernote-image-attributes), 
but `imageShape` was removed at https://github.com/StudioJunkyard/summernote-image-attributes/commit/c098012503e39451cd00749908e34752593ae5dc
Then I find this plugin and notice that no javascript files here.

**Comment by DennisSuitters** [comment]
Sorry for the delay. Life got in the way of me keeping things up to date.
I can only assume that I hadn't added the actual plugin itself as I was testing it on my local machine, but I am in the process of rectifying that, so it should be available shortly (hopefully today).

**Comment by DennisSuitters** [comment]
The script has been added now, didn't take as long as thought it would. I'll close this Issue now, if you find problems you can open a new issue and report.
